import type { PricingPlan } from "./types";
import { brandContent } from "./brand";

export const pricingContent = {
  heading: "Pilihan Paket Kasir untuk Mengamankan Omzet",
  subheading: "Pilih paket yang sesuai dengan jumlah cabang dan skala usaha Anda.",
  yearlyDiscountNote: "Hemat 2 bulan dengan langganan tahunan",
  plans: [
    {
      id: "gratis",
      name: "Gratis",
      description: "Untuk usaha pemula yang ingin mencoba kasir digital dasar dengan kuota terbatas.",
      monthlyPrice: 0,
      yearlyPricePerMonth: 0,
      outletLimit: "1 Cabang",
      deviceLimit: "1 Perangkat",
      ctaText: "Mulai Gratis",
      ctaHref: brandContent.appUrl,
      features: [
        { name: "Maksimal 50 Transaksi / Hari", included: true },
        { name: "Pencatatan Transaksi Kasir Dasar", included: true },
        { name: "Cetak Struk Transaksi", included: true },
        { name: "Tanpa Pengaman Selisih Laci", included: false },
        { name: "Tanpa Manajemen Bahan Baku", included: false },
      ],
    },
    {
      id: "warung",
      name: "Warung",
      description: "Untuk 1 toko yang butuh transaksi lancar tanpa batas kuota dan bebas selisih uang laci.",
      monthlyPrice: 99000,
      yearlyPricePerMonth: 79000,
      outletLimit: "1 Cabang",
      deviceLimit: "Maks. 2 Perangkat",
      ctaText: "Pilih Warung",
      ctaHref: brandContent.appUrl,
      features: [
        { name: "Transaksi Bebas Tanpa Kuota", included: true },
        { name: "Hitung Laci Tertutup Tiap Shift", included: true },
        { name: "Cetak Struk & Laporan Kasir", included: true },
        { name: "Izin Pembatalan Pesanan", included: true },
        { name: "Dasbor Banyak Cabang", included: false },
      ],
    },
    {
      id: "bisnis",
      name: "Bisnis",
      description: "Paket paling diminati pemilik usaha 2-5 cabang yang ingin kontrol sentral.",
      monthlyPrice: 249000,
      yearlyPricePerMonth: 199000,
      highlighted: true,
      outletLimit: "Hingga 5 Cabang",
      deviceLimit: "Perangkat Tak Terbatas",
      ctaText: "Pilih Paket Bisnis",
      ctaHref: brandContent.appUrl,
      features: [
        { name: "Semua fitur Paket Warung", included: true },
        { name: "Izin Pembatalan + PIN Manajer", included: true },
        { name: "Kunci Aplikasi di Layar Kasir", included: true },
        { name: "Pencatatan Stok & Bahan Terbuang", included: true },
        { name: "Dasbor Konsolidasi Semua Cabang", included: true },
      ],
    },
    {
      id: "enterprise",
      name: "Enterprise",
      description: "Untuk jaringan cabang besar yang butuh modul kustom dan pendampingan khusus.",
      monthlyPrice: null,
      yearlyPricePerMonth: null,
      customPrice: true,
      outletLimit: "Cabang Tak Terbatas",
      deviceLimit: "Perangkat Tak Terbatas",
      ctaText: "Hubungi Sales",
      ctaHref: brandContent.contacts.whatsappUrl,
      features: [
        { name: "Semua fitur Paket Bisnis", included: true },
        { name: "Pengembangan Modul Custom Sesuai SOP", included: true },
        { name: "Integrasi API & Laporan Pembukuan Toko", included: true },
        { name: "Server Dedicated & Dukungan Khusus", included: true },
        { name: "Pendampingan Khusus & Training Staf", included: true },
      ],
    },
  ] satisfies PricingPlan[],
} as const;
