import type { PricingPlan } from "./types";
import { brandContent } from "./brand";

export const pricingContent = {
  heading: "Pilihan Paket Kasir untuk Mengamankan Omzet",
  subheading: "Pilih paket yang sesuai dengan jumlah cabang dan skala usaha Anda.",
  yearlyDiscountNote: "Hemat 2 bulan dengan langganan tahunan",
  plans: [
    {
      id: "warung",
      name: "Warung",
      description: "Cocok untuk 1 toko yang ingin kasir lancar tanpa internet dan bebas selisih uang laci.",
      monthlyPrice: 99000,
      yearlyPricePerMonth: 79000,
      outletLimit: "1 Cabang",
      deviceLimit: "Maks. 2 Perangkat",
      ctaText: "Mulai Sekarang",
      ctaHref: brandContent.appUrl,
      features: [
        { name: "Kasir Lancar Tanpa Internet", included: true },
        { name: "Hitung Laci Tertutup Tiap Shift", included: true },
        { name: "Cetak Struk & Laporan Kasir", included: true },
        { name: "Izin Pembatalan Pesanan", included: true },
        { name: "Dasbor Banyak Cabang", included: false },
        { name: "Kunci Aplikasi di Layar Kasir", included: false },
      ],
    },
    {
      id: "bisnis",
      name: "Bisnis",
      description: "Paket paling diminati pemilik usaha 2-10 cabang yang ingin kontrol sentral.",
      monthlyPrice: 249000,
      yearlyPricePerMonth: 199000,
      highlighted: true,
      outletLimit: "Hingga 5 Cabang",
      deviceLimit: "Perangkat Tak Terbatas",
      ctaText: "Pilih Paket Bisnis",
      ctaHref: brandContent.appUrl,
      features: [
        { name: "Kasir Lancar Tanpa Internet", included: true },
        { name: "Hitung Laci Tertutup Tiap Shift", included: true },
        { name: "Izin Pembatalan + PIN Manajer", included: true },
        { name: "Kunci Aplikasi di Layar Kasir", included: true },
        { name: "Pencatatan Stok & Bahan Terbuang", included: true },
        { name: "Dasbor Konsolidasi Semua Cabang", included: true },
      ],
    },
    {
      id: "enterprise",
      name: "Enterprise",
      description: "Untuk jaringan retail dan resto besar (>10 cabang) dengan kebutuhan kustom dan pendampingan.",
      monthlyPrice: 599000,
      yearlyPricePerMonth: 499000,
      outletLimit: "Cabang Tak Terbatas",
      deviceLimit: "Perangkat Tak Terbatas",
      ctaText: "Hubungi Sales",
      ctaHref: brandContent.contacts.whatsappUrl,
      features: [
        { name: "Semua fitur Paket Bisnis", included: true },
        { name: "Catatan Riwayat Kas Lengkap & Permanen", included: true },
        { name: "Server Prioritas & Dukungan Khusus", included: true },
        { name: "Integrasi Laporan Pembukuan Toko", included: true },
        { name: "Pendampingan Khusus & Training Staf", included: true },
        { name: "Atur Hak Akses Karyawan Bebas", included: true },
      ],
    },
  ] satisfies PricingPlan[],
} as const;
